### ISSUE TITLE
`$` is side-effect free yet calls `$` on all values

### ISSUE THREAD

**Issue by disruptek** [arnetheduck/nim-result#10]
All values in Result objects must have a side-effect-free `$`.  Is this a design decision intended to impose upon the user?

I've been tolerating it, but it doesn't really feel like a requirement that should exist.

**Comment by arnetheduck** [comment]
well yeah. the only reason against I can think of is that stdlib `$` doesn't suggest it creating an inconsistency.. I mean.. can you think of a legitimate use case that feels natural to the caller of `$` where it wouldn't be side-effect-free?

in my favour, you can work around it for any library type that's dumb enough to actually do side effects in there by specializing (I think)

**Comment by disruptek** [comment]
Don't get me wrong -- I don't have a strong opinion about this, but for one thing, it may be an obstruction to adoption, perhaps even a deal-breaking obstacle.  With calls into FFI, it's of dubious value.

**Comment by arnetheduck** [comment]
calls into FFI can be decorated with a `{.noSideEffects.}: call()` thingie I think - arguably if the FFI is sideeffect-free it should tell the nim compiler so, so that it can deduce the right things. 

but there is that point yes, that it's ultimately perhaps not for `nim-result` to have an opinion about. some concrete cases would help inform a decision..

**Comment by disruptek** [comment]
What it comes down to is, I would rather provide a `$` to `Result` _if I want it, and to my specification_ than have to provide side-effect free `$` to every single type that I want to use `Result` with.  This is a library that is supposed to add value to my work, not work without value.

https://github.com/disruptek/gittyup/blob/master/gittyup.nim#L576

**Comment by arnetheduck** [comment]
well, nim should be able to deduce side-effect-freeness and not complain in the majority of cases, no?
