### ISSUE TITLE
Add flatten and filter

### ISSUE THREAD

**Issue by schneiderfelipe** [arnetheduck/nim-result#14]
It would be nice to have both [`flatten`](https://nim-lang.org/docs/options.html#flatten%2COption%5BOption%5BA%5D%5D) and [`filter`](https://nim-lang.org/docs/options.html#filter%2COption%5BT%5D%2Cproc%28T%29), which are present in the standard [`options` module](https://nim-lang.org/docs/options.html). That would cover the whole `options` API and make `results` an easy (almost) drop-in replacement for `options`, as all other functions in the `options` module are already covered.

**Comment by arnetheduck** [comment]
Sounds reasonable, though `filter` is a bit .. odd - it would likely need to return an `Option[E]`

**Comment by arnetheduck** [comment]
#20
