### ISSUE TITLE
A couple of ideas

### ISSUE THREAD

**Issue by yglukhov** [arnetheduck/nim-result#8]
Some ideas to make it more ergonomic.
```nim
import result

# Idea 1. Allows using ok(myValue), and err(myError) in the context of a proc
template ok*[T](v: T): auto = typeof(result).ok(v)
template err*[T](v: T): auto = typeof(result).err(v)

# Idea 2. Allows for nicer if conditions.
template `?=`*(v: untyped{nkIdent}, vv: Result): bool =
  (let v = vv; v.isOk)

proc foo(): Result[int, string] =
  result = ok(5)
#  result = err("asdfag")

if f ?= foo():
  echo f[]
```

Also `:=` can be used instead of `?=`.

**Comment by yglukhov** [comment]
Even better condition:
```nim
template `:=`*[T, E](v: untyped{nkIdent}, vv: Result[T, E]): bool =
  (let vr = vv; let v = if vr.isOk: vr[] else: default(typeof(vr[])); vr.isOk)

proc foo(): Result[int, string] =
  result = ok(5)
#  result = err("asdfag")

if f := foo():
  echo f
```

**Comment by arnetheduck** [comment]
nice, with `:=`

one thing about `if (let ...`: what would it look like to make it available in the else branch too? 

you'll potentially want to deal with the error there, but it's not in scope

**Comment by disruptek** [comment]
There's no reason not to open a new scope in which to capture it, right?

**Comment by disruptek** [comment]
Ah, because then we divide the scope for the branches.  Just a tedious template solution, then?

**Comment by arnetheduck** [comment]
yeah something like:
```
block:
 let r = vv
 if r.isok:
  ..
 else:
```

but that comes with its own problems I guess, for example the `unsafeGet` that might upset any static analysis

**Comment by arnetheduck** [comment]
er, maybe not - that won't work.. I think :/

**Comment by yglukhov** [comment]
Yeah, err analysis is more of a case stmt:
```nim
matchResult case foo()
of ok(f):
  echo "yay: ", f
of err(theErr):
  echo "too bad: ", theErr
```

**Comment by disruptek** [comment]
Oh that would tick all the boxes.

**Comment by arnetheduck** [comment]
re idea 1: https://github.com/arnetheduck/nim-result/blob/master/result.nim#L517

**Comment by disruptek** [comment]
Not a fan of adding control-flow there.

**Comment by yglukhov** [comment]
Oh I didn't notice that template. But +1 to @disruptek. Implicit return feels too unnatural.

**Comment by disruptek** [comment]
I'm using a `:=` and find that (eg. in tests) you might want a `{.used.}` as in the following:

```nim
template v: auto {.used.} = unsafeGet(vr)
```

My use-case is that my `:=` adds a `defer:` to free the LHS result value, and the body of the `:=` is processed in the event of an error.

```nim
block:
  repo, code := openRepository(directory):
    case code:
    of grcNotFound:
       echo directory, " does not exist"
    else:
       echo "error: ", code
    break
  echo "repo state: ", repo.repositoryState
echo "no repo in memory"
```

I think I want `go` syntax, though, because i want the error value to be explicitly named and not merely injected into the template.  Also, I want it to survive outside of my error-handling block so that fall-through there is a "feature".  Here's a contrived example:

```nim
while true:
  repo, code := openRepository(directory):
    if code != grcNotFound or directory.isRootDir:
      echo "unrecoverable error"
      return
  case code:
  of grcOk:
    echo "found a repo in state: ", repo.repositoryState
    break
  else:
     echo "trying parent..."
     directory = directory.parentDir
```

I guess `(success, failure)` will be easier to implement than `success, failure` due to compiler parsing rules, but whatever.

**Comment by arnetheduck** [comment]
the go syntax is problematic in that both symbols "exist" in scope and one of them is uninitialized / default-initialized meaning you can't use it for values that don't have a meaningful default (ie `float` - is it 0, nan or binary all-zeroes)?)

**Comment by arnetheduck** [comment]
@disruptek but feel free to open a new issue where we can discuss it separately
